version: "3.9"

services:
  api:
    build:
      context: .
    ports:
      - 80:80


#  pg:
#    image: postgres:latest
#    environment:
#      POSTGRES_USER: flask_app
#      POSTGRES_PASSWORD: flask_app_password
#      POSTGRES_DB: flask_app